resolver: nightly-2022-09-30 # GHC-9.2.4

packages:
- .

# so that `stack build --copy-bins` puts bin here
local-bin-path: .

extra-deps:

- github: GrammaticalFramework/gf-core
  commit: b59fe24c118826e91709170c97913a8db79374af
- multipart-0.2.0@sha256:b8770e3ff6089be4dd089a8250894b31287cca671f3d258190a505f9351fa8a9,1084
- cgi-3001.5.0.0@sha256:3d1193a328d5f627a021a0ef3927c1ae41dd341e32dba612fed52d0e3a6df056,2990
- pgf2-1.3.0

# Location of the C runtime
extra-lib-dirs:
- /usr/local/lib

# path for the C runtime is also needed for the linker, see
# https://ro-che.info/articles/2020-04-07-haskell-local-c-library
ghc-options:
  "$locals": -optl=-Wl,-rpath,/usr/local/lib

allow-newer: true